name: BuildDocs
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install yfm
        shell: bash
        run: |
          npm i @doc-tools/docs -g

      - name: build docs
        shell: pwsh
        run: |
          ./.scripts/buildDoc.ps1

      - name: publish docs
        shell: bash
        env:
          YFM_STORAGE_KEY_ID: ${{ secrets.KEY_ID }}
          YFM_STORAGE_SECRET_KEY: ${{ secrets.KEY }}
        run: |
          cd ..
          yfm -i ./ycps-docs -o ./ycps-docs-html \
          --publish \
          --storageEndpoint ${{ secrets.STORAGE_ENDPOINT }} \
          --storageBucket ${{ secrets.STORAGE_BUCKET }}
          